### ISSUE TITLE
Seems unfinished

### ISSUE THREAD

**Issue by guix77** [kurtisdunn/Drupal-8-Theme-Bootstrap-3-SASS#2]
It's a shame :)

**Comment by kurtisdunn** [comment]
I ran out of time. I have another Drupal project coming up in a couple of months, so Im sure I'll get it up to scratch. Feel free to help :)

**Comment by guix77** [comment]
No pb I know that sound ;) Not much time from me too... But I lost a little time trying to use your repo LOL ! Just sayin', you could say it's not really prod-ready on the README ;) Chears

**Comment by kurtisdunn** [comment]
I updated it. Thanks for letting me know.

**Comment by guix77** [comment]
Thanks, yup maybe in a few months if I can change my job :)
