### ISSUE TITLE
Error : Waiting for localhost

### ISSUE THREAD

**Issue by ChandeepKhosa** [kurtisdunn/Drupal-8-Theme-Bootstrap-3-SASS#3]
I followed your steps : clone repo; cd into theme; npm install; bower install; gulp

It then launched the 2 gulp-notify commands and kept trying to load, but never got past the white screen.

Browser (localhost not loading) http://screencast.com/t/WDF5coS32C
Terminal (Bower install) http://screencast.com/t/ZwnSPzxxE
Terminal (Gulp) http://screencast.com/t/NyZQe1wiVGW

**Comment by kurtisdunn** [comment]
gulp-notify isnt supported on windows.

**Comment by ChandeepKhosa** [comment]
I'm not using Windows, I'm using Mac
